# Generated by Django 4.2.8 on 2024-01-05 14:10

from django.db import migrations, models
import django.db.models.deletion
import swapper

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0006_alter_organization_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "organization_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "swappable": swapper.swappable_setting('projects', 'Project'),
            },
            bases=("organizations.organization",),
        ),
    ]
