# Generated by Django 4.2.6 on 2023-10-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("csw", "0003_alter_cswconfig_contact_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cswconfig",
            name="contact_postalcode",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
