# Generated by Django 4.2.8 on 2023-12-19 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layer",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="layers",
                to="maps.layergroup",
            ),
        ),
    ]
