# Generated by Django 4.2.8 on 2023-12-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0002_alter_layer_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layer",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="map",
            name="slug",
            field=models.SlugField(max_length=150),
        ),
        migrations.AlterField(
            model_name="source",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
