# Generated by Django 4.2.8 on 2023-12-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0003_alter_layer_slug_alter_map_slug_alter_source_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="map",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")], default="private", max_length=10
            ),
        ),
    ]
