# Generated by Django 4.2.8 on 2024-01-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0005_portal_portalmap_portal_portal_unique_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="map",
            name="slug",
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
