# Generated by Django 4.2.8 on 2024-01-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0006_alter_map_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="downloadable",
            field=models.BooleanField(default=False),
        ),
    ]
