# Generated by Django 4.2.8 on 2024-02-22 10:49

from django.db import migrations, models
import metadata_catalogue.maps.models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0007_layer_downloadable"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="layer",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="layergroup",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="layergroup",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="map",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to=metadata_catalogue.maps.models.logo_folder),
        ),
    ]
