# Generated by Django 4.2.8 on 2024-03-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0008_layer_description_layer_link_layergroup_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="is_basemap",
            field=models.BooleanField(default=False, verbose_name="Is basemap"),
        ),
        migrations.AddField(
            model_name="layer",
            name="legend",
            field=models.TextField(blank=True, null=True),
        ),
    ]
