# Generated by Django 4.2.8 on 2024-03-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0010_map_legends_alter_layer_legend"),
    ]

    operations = [
        migrations.AddField(
            model_name="map",
            name="basemap_config",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
