# Generated by Django 4.2.8 on 2024-03-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0011_map_basemap_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="map",
            name="config",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
