# Generated by Django 4.2.8 on 2024-03-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0012_map_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="hidden",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="layer",
            name="is_lazy",
            field=models.BooleanField(default=True, verbose_name="Is lazy"),
        ),
    ]
