# Generated by Django 4.2.8 on 2024-04-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0013_layer_hidden_layer_is_lazy"),
    ]

    operations = [
        migrations.AddField(
            model_name="layergroup",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddConstraint(
            model_name="layergroup",
            constraint=models.UniqueConstraint(models.F("slug"), name="group unique slug"),
        ),
    ]
