# Generated by Django 4.2.8 on 2024-04-30 10:39

from django.db import migrations, models
import metadata_catalogue.maps.models


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0015_source_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="metadata",
            field=models.JSONField(blank=True, default=metadata_catalogue.maps.models.empty_json),
        ),
    ]
