# Generated by Django 4.2.8 on 2024-07-19 14:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import metadata_catalogue.maps.models
import metadata_catalogue.maps.storage


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0017_remove_rastersource_attribution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="layergroup",
            name="bbox",
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326, blank=True),
        ),
        migrations.AddField(
            model_name="layergroup",
            name="is_open",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="rastersource",
            name="original_data",
            field=models.FileField(
                blank=True,
                null=True,
                storage=metadata_catalogue.maps.storage.OverwriteStorage,
                upload_to=metadata_catalogue.maps.models.layers_folder,
            ),
        ),
        migrations.AlterField(
            model_name="rastersource",
            name="source",
            field=models.FileField(
                blank=True,
                null=True,
                storage=metadata_catalogue.maps.storage.OverwriteStorage,
                upload_to=metadata_catalogue.maps.models.layers_folder,
            ),
        ),
        migrations.AlterField(
            model_name="vectorsource",
            name="original_data",
            field=models.FileField(
                blank=True,
                null=True,
                storage=metadata_catalogue.maps.storage.OverwriteStorage,
                upload_to=metadata_catalogue.maps.models.layers_folder,
            ),
        ),
        migrations.AlterField(
            model_name="vectorsource",
            name="source",
            field=models.FileField(
                blank=True,
                null=True,
                storage=metadata_catalogue.maps.storage.OverwriteStorage,
                upload_to=metadata_catalogue.maps.models.layers_folder,
            ),
        ),
    ]
