# Generated by Django 4.2.8 on 2024-07-26 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("maps", "0018_layergroup_bbox_layergroup_is_open_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portalmap",
            name="external_cover",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portalmap",
            name="external_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portalmap",
            name="external_subtitle",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portalmap",
            name="external_title",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="portalmap",
            name="map",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portals",
                to="maps.map",
            ),
        ),
    ]
