#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py wait_for_database

if [ "$DJANGO_ENV" == "local" ]
then
  python manage.py migrate
  python manage.py setup
  exec python manage.py runserver_plus 0.0.0.0:8000
else
  python /app/manage.py collectstatic --noinput
  exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:8000 --chdir=/app
fi
