# Generated by Django 4.2.7 on 2023-12-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="hero_text",
            field=models.CharField(help_text="Write an introduction for the website", max_length=255),
        ),
    ]
