# Generated by Django 4.2.7 on 2023-12-08 10:56

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataReportPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("subtitle", models.TextField(blank=True)),
                ("authors", models.TextField(blank=True)),
                ("place", models.CharField(blank=True, max_length=500)),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("keywords", models.TextField(blank=True)),
                ("metadata_introduction", wagtail.fields.RichTextField(blank=True, null=True)),
                ("metadata_datastructure", wagtail.fields.RichTextField(blank=True, null=True)),
                ("metadata_geografic_definition", models.TextField(blank=True, null=True)),
                ("metadata_taxonomy", models.TextField(blank=True, null=True)),
                ("metadata_timerange_start", models.DateTimeField(blank=True, null=True)),
                ("metadata_timerange_end", models.DateTimeField(blank=True, null=True)),
                ("metadata_collection_methods", wagtail.fields.RichTextField(blank=True, null=True)),
                ("metadata_study_scope", models.TextField(blank=True, null=True)),
                ("metadata_study_description", models.TextField(blank=True, null=True)),
                ("metadata_qc", models.TextField(blank=True, null=True)),
                ("data", wagtail.fields.RichTextField(blank=True, null=True)),
                ("guidelines", wagtail.fields.RichTextField(blank=True, null=True)),
                ("additional_info", wagtail.fields.RichTextField(blank=True, null=True)),
                ("references", wagtail.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="DataReportsIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("introduction", models.TextField(blank=True, help_text="Text to describe the page")),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Landscape mode only; horizontal width between 1000px and 3000px.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
