# Generated by Django 4.2.8 on 2023-12-12 12:58

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datareportpage",
            options={"permissions": [("change_publishing_fields", "Can change the fields related to publishing")]},
        ),
        migrations.AddField(
            model_name="datareportpage",
            name="isbn",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datareportpage",
            name="number",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datareportpage",
            name="summary",
            field=wagtail.fields.RichTextField(blank=True, max_length=4000, null=True),
        ),
    ]
