# Generated by Django 4.2.6 on 2023-10-27 08:02

from django.db import migrations, models

QUERY = """
CREATE FUNCTION immutable_hash(VARIADIC entries text[])
RETURNS bytea
language sql
IMMUTABLE PARALLEL SAFE
return sha224(convert_to(cast(entries as text), 'UTF8'));

alter table datasets_person add column "hash" bytea GENERATED ALWAYS AS (immutable_hash(first_name, last_name, country_id::text, position, email, belongs_to_id::text)) STORED unique;
"""

REVERSE = """
ALTER TABLE datasets_person DROP COLUMN hash;
DROP FUNCTION immutable_hash;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("datasets", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunSQL(QUERY, REVERSE)],
            state_operations=[migrations.AddField(model_name="person", name="hash", field=models.BinaryField())],
        )
    ]
