name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ['master', 'main']
    paths-ignore: ['docs/**']

  push:
    branches: ['master', 'main']
    paths-ignore: ['docs/**']

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      # Consider using pre-commit.ci for open source project
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Setup secrets
        run: cd setup && docker compose up --build && cd ..

      - name: Build the Stack
        run: docker compose --profile dev --env-file secrets/docker build

      - name: Run DB Migrations
        run: docker compose --profile dev --env-file secrets/docker run --rm django-dev python manage.py migrate

      - name: Run Django Tests
        run: docker compose --profile dev --env-file secrets/docker run django-dev pytest

      - name: Load fixtures
        run: docker compose --profile dev --env-file secrets/docker run --rm django-dev python manage.py loaddata datasets.json

      - name: Run Bruno Tests
        run: docker compose --profile dev --profile test --env-file secrets/docker run bruno

      - name: Tear down the Stack
        run: docker compose --profile dev --env-file secrets/docker down
